analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    avoid_catches_without_on_clauses: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    specify_nonobvious_property_types: false
    sort_constructors_first: false
    public_member_api_docs: false
    prefer_single_quotes: true
    prefer_const_constructors: true
    avoid_print: true
    prefer_final_fields: true
