name: sfb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flex_color_scheme: ^8.3.1
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  injectable: ^2.5.2
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.9.0
  build_runner: ^2.10.1

flutter:
  uses-material-design: true
