name: sfb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  equatable: ^2.0.7
  flex_color_scheme: ^8.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.2.0
  go_router: ^16.3.0
  injectable: ^2.5.2
  intl: any
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  injectable_generator: ^2.8.0
  build_runner: ^2.7.1

flutter:
  generate: true
  uses-material-design: true
